version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/doggo
      - SPRING_DATASOURCE_USERNAME=dog
      - SPRING_DATASOURCE_PASSWORD=dog
    depends_on:
      - db
    networks:
      - doggo-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=doggo
      - POSTGRES_USER=dog
      - POSTGRES_PASSWORD=dog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - doggo-network

volumes:
  postgres_data:

networks:
  doggo-network:
    driver: bridge
